In [1]:
import numpy as np
import sympy as sym

In [2]:
J0 = np.array([[1,0,0,0],[0,1,0,0],[0,0,-1,0],[0,0,0,-1]])
J1 = np.array([[0,0,0,1],[0,0,1,0],[0,-1,0,0],[-1,0,0,0]])
J2 = np.array([[0,0,0,-1j],[0,0,1j,0],[0,1j,0,0],[-1j,0,0,0]])
J3 = np.array([[0,0,1,0],[0,0,0,-1],[-1,0,0,0],[0,1,0,0]])

J = np.array([J0,J1,J2,J3])

In [19]:
Nuv = np.array([[1,0,0,0],[0,-1,0,0],[0,0,-1,0],[0,0,0,-1]])
Nuv

array([[ 1,  0,  0,  0],
       [ 0, -1,  0,  0],
       [ 0,  0, -1,  0],
       [ 0,  0,  0, -1]])

In [22]:
def CliffAlgebra(n1,n2):
    a =  Nuv[n1][n2]
    return 2*a*np.eye(4)
CliffAlgebra(1,2)

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [23]:
def AntiConmutator(n1,n2):
    return ((J[n1]@J[n2])+(J[n2]@J[n1]))
AntiConmutator(1,2)

array([[0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j],
       [0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j],
       [0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j],
       [0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j]])

In [26]:
print('Por lo anterior, se observa que se cumple el álgebra de Clifford generada por el anticonmutador de las matrices del grupo.\nEn la mayoría de los casos el anticonmutador es una matriz de ceros.\n')

Por lo anterior, se observa que se cumple el álgebra de Clifford generada por el anticonmutador de las matrices del grupo.
En la mayoría de los casos el anticonmutador es una matriz de ceros.

