In [1]:
import numpy as np

In [35]:
A = np.array([[1,0,0],[5,1,0],[-2,3,-1]])
B = np.array([[4,-2,1],[0,3,7],[0,0,2]])
A,B

(array([[ 1,  0,  0],
        [ 5,  1,  0],
        [-2,  3, -1]]),
 array([[ 4, -2,  1],
        [ 0,  3,  7],
        [ 0,  0,  2]]))

In [36]:
New = np.zeros((3,3))
New

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [37]:
for i in range(len(A)):
    for j in range(len(A)):
        for k in range(len(A)):
            New[i][j] += A[i][k]*B[k][j]
New

array([[ 4., -2.,  1.],
       [20., -7., 12.],
       [-8., 13., 17.]])