In [10]:
%matplotlib notebook
import numpy as np
import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d import axes3d

In [11]:
A = np.array([[3,-1,-1],[-1.,3.,1.],[2,1,4]])
b = np.array([1.,3.,7.])
A.shape[1]

3

In [62]:
def SOR(A,b,x0, w, itmax=1000, tolerancia= 10e-3):
    x = x0.copy()
    it_min = 0
    for it in range(1, 1000):
        xn = np.zeros(len(A[0]))
        for i in range(len(A[0])):
            sum_1 = np.dot(A[i,:i], xn[:i])
            sum_2 = np.dot(A[i,i+1:], x[i+1:])
            xn[i] = (1-w)*x[i] + (w*(b[i] - sum_1 -sum_2)/A[i,i])
            
        residuo = np.linalg.norm(np.dot(A,x)-b)
        if np.allclose(residuo,tolerancia,atol=tolerancia):
            it_min = it
            break
        x = xn
    return x,it_min

In [63]:
SOR(A,b,np.zeros(3),1.4)

(array([0.99641905, 1.00041338, 1.00400341]), 216)

In [64]:
wi = np.linspace(0,2,50)
it_min = 1000

for i in range(1,len(wi)-1):
    a = SOR(A,b,np.zeros(3),wi[i])
    print(a,wi[i])

(array([0.99917354, 0.99365139, 1.00578336]), 204) 0.04081632653061224
(array([0.99910275, 0.99351062, 1.00585288]), 100) 0.08163265306122448
(array([0.9990894 , 0.99373272, 1.00558956]), 66) 0.12244897959183673
(array([0.99907881, 0.99396499, 1.00531997]), 49) 0.16326530612244897
(array([0.99894126, 0.9934932 , 1.00567728]), 38) 0.2040816326530612
(array([0.99886257, 0.9933819 , 1.00570755]), 31) 0.24489795918367346
(array([0.99878103, 0.99327849, 1.00572661]), 26) 0.2857142857142857
(array([0.99893586, 0.9943382 , 1.00474707]), 23) 0.32653061224489793
(array([0.99886839, 0.99429458, 1.00471914]), 20) 0.36734693877551017
(array([0.99852285, 0.99303889, 1.00569608]), 17) 0.4081632653061224
(array([0.99837761, 0.99275719, 1.00584199]), 15) 0.44897959183673464
(array([0.9986646 , 0.99426648, 1.00453096]), 14) 0.4897959183673469
(array([0.99812633, 0.99246898, 1.00588037]), 12) 0.5306122448979591
(array([0.99817475, 0.99301684, 1.00534491]), 11) 0.5714285714285714
(array([0.99809569, 0.99

<ipython-input-62-37570cf053df>:9: RuntimeWarning: overflow encountered in double_scalars
  xn[i] = (1-w)*x[i] + (w*(b[i] - sum_1 -sum_2)/A[i,i])
<ipython-input-62-37570cf053df>:9: RuntimeWarning: invalid value encountered in double_scalars
  xn[i] = (1-w)*x[i] + (w*(b[i] - sum_1 -sum_2)/A[i,i])


In [50]:
print('Se observa que cuando el w excede 1.3 los resultados son muy imprecisos al obtener números muy grandes y las iteraciones incrementan drásticamente.\n')

Se observa que cuando el w excede 1.3 los resultados son muy imprecisos al obtener números muy grandes y las iteraciones incrementan drásticamente.



In [58]:
#Para w<1.3

we = np.linspace(0,1.3,50)
it_min = 1000
wmin = 0

for i in range(1,len(wi)-1):
    a = SOR(A,b,np.zeros(3),we[i])[-1]
    if a < it_min:
        it_min = a
        wmin = we[i]
        
it_min,wmin

(5, 0.9020408163265307)

In [60]:
print('Se observa que la cantidad mínima de iteraciones para el método es 5 con un w = 0.90204..')

Se observa que la cantidad mínima de iteraciones para el método es 5 con un w = 0.90204..
